Пахомов Леонид 6312-100503D, Лабораторная работа 3
itsecd/ptm-3 pull request #21
Opened 2023-11-22 10:02 UTC by Sonya-From-IBAS

В этой работе с помощью регулярных выражений нужно было найти все неправильные данные из csv файла и посчитать хэш, записав его в result.json

2023-11-22 12:32 UTC, alxmcs requested changes

2023-11-22 12:32 UTC, alxmcs commented on main.py
> +    "longitude":"^-?\d{1,3}\.\d+$",
Я хз, почему в большинстве pr игнорируется то, что широта/долгота имеет ограничения на значения, которые она может принимать. Но это надо учесть в регулярном выражении

2023-11-22 16:53 UTC, Sonya-From-IBAS commented
Поправил

2023-11-23 05:05 UTC, alxmcs approved these changes

2023-11-23 05:05 UTC, alxmcs commented
Зачтено

2023-11-23 05:05 UTC, closed without merging