Кадников Егор Вадимович 6313 Лаб. 3 вариант 51
itsecd/ptm-3 pull request #37
Opened 2023-11-26 13:44 UTC by acebiscuits

[нужно было создать регулярные выражения для валидации файла.](https://github.com/itsecd/ptm-3/pull/36)

2023-11-28 10:57 UTC, alxmcs requested changes

2023-11-28 10:57 UTC, alxmcs commented on checksum.py
> +    global k
Это кто и зачем он тут нужен?

2023-11-28 10:57 UTC, alxmcs commented on checksum.py
> +    print('len: ',len(neded_indexes))
Мы еще на 2 курсе договорились, что `print` - харам

2023-11-28 10:57 UTC, alxmcs commented on checksum.py
> +                print(index)
Аналогично

2023-11-28 10:57 UTC, alxmcs commented on checksum.py
> +            print(f"{title}")
Аналогично

2023-11-28 10:57 UTC, alxmcs commented on checksum.py
> +    with open("51.csv", 'r', encoding="utf-16") as f:
Вынести в параметры функции

2023-11-29 06:42 UTC, alxmcs requested changes
Теперь логирование пропало из кода в принципе. что тебе помешало использовать какой-нибудь `logging` вместо `print`?

2023-11-29 08:48 UTC, acebiscuits commented
это лаба про регулярки, тут логирование по сути не нужно вообще

2023-11-29 10:35 UTC, alxmcs requested changes
Раз уж ты начал логировать какие-то операции в своем софте, то доведи это до приемлемого состояния

2023-11-29 17:34 UTC, acebiscuits commented
добавил логинг

2023-11-30 08:54 UTC, alxmcs approved these changes
Зачтено

2023-11-30 08:54 UTC, closed without merging