Челаев Петр 6312. 42 вариант
itsecd/ptm-3 pull request #53
Opened 2023-12-05 16:47 UTC by PripyatskyPrometheus

Сделали fork данного репозитория.
Получили csv-файл в соответствии со своим вариантом.
Произвели валидацию файла с использованием регулярных выражений.
На основе номеров невалидных строк подсчитали контрольную сумму.

2023-12-07 14:42 UTC, alxmcs requested changes

2023-12-09 07:59 UTC, alxmcs requested changes

2023-12-09 07:59 UTC, alxmcs commented on main.py
> +    "longitude": r"^-? \d{1,3} \. \d+$",
Все еще не учтено ограничение на значения WGS84 долготы

2023-12-09 10:33 UTC, PripyatskyPrometheus commented on main.py
> +    "longitude": r"^-? \d{1,3} \. \d+$",
Пардон, я подумал, вы во втором ревью просто пояснили первое

2023-12-10 07:31 UTC, alxmcs approved these changes
Зачтено

2023-12-10 07:31 UTC, closed without merging