Lab - 2 TMP
itsecd/ptm-3 pull request #9
Opened 2023-11-16 17:57 UTC by ZamotohinaMaria

Функция и словарь для валидации данных находятся в файле checksum.py. 
Основной код, в котором происходит получение данных из csv файла и вызова основных функций - в файле main.py
В файле valid_data.csv находится набор уже исправленных данных.
Файл try.json использовался, чтобы настроить сериализацию в json файл

2023-11-18 07:58 UTC, alxmcs requested changes
Акшон отработал успешно, к регулярным выражениям у меня вопросов нет.
Но хотелось бы, чтобы пара мелочей по коду была поправлена.

2023-11-18 07:58 UTC, alxmcs commented on try.json
Этот файл точно нужен в репозитории?

2023-11-18 07:58 UTC, alxmcs commented on main.py
> +            writer.writerow(valid_data_to_csv[i])
Было бы неплохо декомпозитровать эту часть кода по функциям и отвязать обработку от имени файла, чтобы софт был (относительно) генерализован

2023-11-27 10:24 UTC, ZamotohinaMaria commented
Необходимые изменения внесены(описаны в коммите)

2023-11-28 10:50 UTC, alxmcs approved these changes
Зачтено

2023-11-28 10:50 UTC, closed without merging